
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import { ThemeProvider } from "@/Components/ThemeProvider";
import MouseMovement from "@/Components/MouseMovement";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-white text-black dark:bg-gray-900 dark:text-white "
      >
        <MouseMovement />
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
          </ThemeProvider>
         

      </body>
    </html>
  );
}


